name: ESLint
on:
  workflow_call:
    inputs:
        extensionName:
          description: 'Extension name'
          required: true
          type: string
        heycartVersion:
          required: false
          type: string
          default: '.auto'
        heycartVersionFallback:
          required: false
          type: string
          default: trunk
        heycart-repository:
          description: The heycart repository to checkout
          type: string
          default: heycart/heycart

jobs:
  run:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: heycart/github-actions/heycart-version@main
        with:
          fallback: ${{ inputs.heycartVersionFallback }}
          repo: ${{ inputs.heycart-repository }}
        id: version
        if: ${{ inputs.heycartVersion == '.auto' || inputs.heycartVersion == '' }}
      - name: Clone Shopware
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.heycart-repository || 'heycart/heycart' }}
          ref: ${{ steps.version.outputs.heycart-version || inputs.heycartVersion }}
      - name: Clone Extension
        uses: actions/checkout@v4
        with:
          path: custom/plugins/${{ inputs.extensionName }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install admin deps
        shell: bash
        working-directory: src/Administration/Resources/app/administration
        run: npm ci --no-audit --no-fund --prefer-offline

      - name: Install Plugin Dependencies
        working-directory: custom/plugins/${{ inputs.extensionName }}/src/Resources/app/administration
        run: npm install --no-audit --no-fund --prefer-offline

      - name: Run ESLint
        working-directory: custom/plugins/${{ inputs.extensionName }}/src/Resources/app/administration
        run: npm run lint
